- name: appsetup
  include_role:
    name: common
    tasks_from: app-setup

- name: manen Setup
  include_role:
    name: common
    tasks_from: maven
    
- name: import data
  # tags:
  # - import
  community.mysql.mysql_db:
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: mysql.manchem.site
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: Systemd Service
  include_role:
    name: common
    tasks_from: systemd