- name: copy catalogue service to system directory
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Reloading the Daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start and enable service
  ansible.builtin.service:
    name: catalogue
    state: restarted # Even app is not running we can restart
    enabled: yes