  - name: Installing MySQL
    ansible.builtin.dnf:
      name: mysql-server 
      state: installed
    
  - name: start and enable service 
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: setting root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1 