- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: NodeJS Configuration
  include_role:
    name: common
    tasks_from: nodejs

- name: copying mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Istalling MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.manchem.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.manchem.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: Systemd Service
  include_role:
    name: common
    tasks_from: systemd