
- name: appsetup
  include_role:
    name: common
    tasks_from: app-setup

- name: NodeJS Configuration
  include_role:
    name: common
    tasks_from: nodejs

- name: Systemd Service
  include_role:
    name: common
    tasks_from: systemd
