- name: Stop the service
  ansible.builtin.service:
    name: "{{ component }}"
    state: stoped

- name: Removing /app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and Extracting thr code
  ansible.builtin.unarchive:
    src: curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/{{ component}}-v{{ app_version }}.zip 
    dest: /app
    remote_src: yes

- name: Install Dependencies
  community.general.npm:
    name: npm
    path: /app

- name: Service Restart
  ansible.builtin.service:
   name: "{{ component }}"
   state: restarted