- name: copy {{ component }} service to system directory
  ansible.builtin.template:
    src: {{ component }}.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: Reloading the Daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start and enable service
  ansible.builtin.service:
    name: {{ component }}
    state: restarted # Even app is not running we can restart
    enabled: yes